// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertMessage = `-- name: InsertMessage :execresult
INSERT INTO messages (tenant_id, session_id, role, content, created_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type InsertMessageParams struct {
	TenantID  string `json:"tenant_id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertMessage,
		arg.TenantID,
		arg.SessionID,
		arg.Role,
		arg.Content,
	)
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, tenant_id, session_id, role, content, created_at
FROM messages
WHERE tenant_id = ? AND session_id = ?
ORDER BY id DESC
LIMIT ?
`

type ListMessagesBySessionParams struct {
	TenantID  string `json:"tenant_id"`
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListMessagesBySession(ctx context.Context, arg ListMessagesBySessionParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, arg.TenantID, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
