// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Message struct {
	ID        int64     `json:"id"`
	TenantID  string    `json:"tenant_id"`
	SessionID string    `json:"session_id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type RuntimeLlmConfig struct {
	TenantID         string    `json:"tenant_id"`
	Provider         string    `json:"provider"`
	Model            string    `json:"model"`
	OpenrouterApiKey string    `json:"openrouter_api_key"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Session struct {
	TenantID      string    `json:"tenant_id"`
	ID            string    `json:"id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	LastMessageAt time.Time `json:"last_message_at"`
}
