// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetRuntimeLLMConfig(ctx context.Context, tenantID string) (RuntimeLlmConfig, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (sql.Result, error)
	ListMessagesBySession(ctx context.Context, arg ListMessagesBySessionParams) ([]Message, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	UpsertRuntimeLLMConfig(ctx context.Context, arg UpsertRuntimeLLMConfigParams) error
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
}

var _ Querier = (*Queries)(nil)
