// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runtime_llm_config.sql

package sqlc

import (
	"context"
)

const getRuntimeLLMConfig = `-- name: GetRuntimeLLMConfig :one
SELECT tenant_id, provider, model, openrouter_api_key, updated_at
FROM runtime_llm_config
WHERE tenant_id = ?
`

func (q *Queries) GetRuntimeLLMConfig(ctx context.Context, tenantID string) (RuntimeLlmConfig, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeLLMConfig, tenantID)
	var i RuntimeLlmConfig
	err := row.Scan(
		&i.TenantID,
		&i.Provider,
		&i.Model,
		&i.OpenrouterApiKey,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRuntimeLLMConfig = `-- name: UpsertRuntimeLLMConfig :exec
INSERT INTO runtime_llm_config (tenant_id, provider, model, openrouter_api_key, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(tenant_id) DO UPDATE SET
  provider = excluded.provider,
  model = excluded.model,
  openrouter_api_key = excluded.openrouter_api_key,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertRuntimeLLMConfigParams struct {
	TenantID         string `json:"tenant_id"`
	Provider         string `json:"provider"`
	Model            string `json:"model"`
	OpenrouterApiKey string `json:"openrouter_api_key"`
}

func (q *Queries) UpsertRuntimeLLMConfig(ctx context.Context, arg UpsertRuntimeLLMConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertRuntimeLLMConfig,
		arg.TenantID,
		arg.Provider,
		arg.Model,
		arg.OpenrouterApiKey,
	)
	return err
}
