// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const listSessions = `-- name: ListSessions :many
SELECT tenant_id, id, created_at, updated_at, last_message_at
FROM sessions
WHERE tenant_id = ?
ORDER BY last_message_at DESC
LIMIT ?
`

type ListSessionsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (tenant_id, id, created_at, updated_at, last_message_at)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(tenant_id, id) DO UPDATE SET updated_at = CURRENT_TIMESTAMP
`

type UpsertSessionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession, arg.TenantID, arg.ID)
	return err
}
